### ISSUE TITLE
Ranger Not working with v3.0

### ISSUE THREAD

**Issue by ironpe** [aws-samples/aws-emr-apache-ranger#79]
CFN with v3.0 is completed successfully, but Ranger admin process isn't running with below error in /tmp/create-ranger-server-output.log:
2022-08-12 11:57:36,358  [E] 'setup_mode' not found in /usr/lib/ranger/ranger-2.1.0-SNAPSHOT-admin/install.properties file while getting....!!
2022-08-12 11:57:36,359  [I] Setup mode is not set. Running DBA steps..
2022-08-12 11:57:39,581  [E] DB schema setup failed! Please contact Administrator.

When executing the install-ranger-admin-server.sh manually, below error occurs.
2022-08-12 14:40:56,702  [I] DB FLAVOR :MYSQL
2022-08-12 14:40:56,702  [I] --------- Verifying Ranger DB connection ---------
2022-08-12 14:40:56,702  [I] Checking connection..
2022-08-12 14:40:56,702  [JISQL] /usr/lib/jvm/jre/bin/java  -cp /usr/lib/ranger/mysql-connector-java-5.1.39.jar:/usr/lib/ranger/ranger-2.1.0-SNAPSHOT-admin/jisql/lib/* org.apache.util.sql.Jisql -driver mysqlconj -cstring jdbc:mysql://emrsecuritywithrangerblogv3-step2-rdsda-resmysqldb-r7gdlpc609fh.cv4yqg77gtv0.us-east-1.rds.amazonaws.com/rangerdb -u 'rangeradmin' -p '********' -noheader -trim -c \;  -query "select 1;"
Fri Aug 12 14:40:56 UTC 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Fri Aug 12 14:40:57 UTC 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:

** BEGIN NESTED EXCEPTION **

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
        at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:735)
        at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:714)
        at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2241)
        at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4267)
        at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1531)
        at org.apache.util.sql.Jisql.run(Jisql.java:339)
        at org.apache.util.sql.Jisql.main(Jisql.java:269)

** END NESTED EXCEPTION **

**Comment by varunrao** [comment]
thanks for opening the issue. Checking

**Comment by ironpe** [comment]
Any check about it?

**Comment by varunrao** [comment]
We are still looking into it. What version of EMR are you using? ave you tried with the older version EMR emr-6.4.0?

**Comment by varunrao** [comment]
This has been fixed now and changes have been pushed. The issue was with the RDS identified values which get truncated after 32 characters causing the Ranger setup to fail.
